### ISSUE TITLE
Can't push

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxRegistry#1]
We also can't push to ToolboxRegistry. even though I can do it from my other machine.  Here is the message from Tower:

Pushing to https://DavidBrainard@github.com/toolboxHub/ToolboxRegistry.git
remote: Permission to toolboxHub/ToolboxRegistry.git denied to DavidBrainard.
fatal: unable to access 'https://DavidBrainard@github.com/toolboxHub/ToolboxRegistry.git/': The requested URL returned error: 403

**Comment by benjamin-heasly** [comment]
I think this is related to https://github.com/ToolboxHub/ToolboxToolbox/issues/5, and a configuration issue specific to the machine.  So I'd like to close this one.
